### ISSUE TITLE
Power/storms for single storm

### ISSUE THREAD

**Issue by thomas-fred** [nismod/open-gira#91]

**Comment by tomalrussell** [comment]
as mentioned in #105, it should be possible to configure an analysis run for single storm or set of storms from the STORM event set, IBTrACS archive, or other future event set.

- use `STORM_SUBSET` as a wildcard, related to a key in config whose value is a list of storm IDs. May want to generate the list programmatically and/or special-case some larger subsets (e.g. "all ibtracs since date", "all STORM", "all")
- have a consistent and flexible way of referring to storms across archive and event set by some ID. For example, derived from (eventset, gcm/historic, basin, year, number within year, sample) for STORM.
